version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm run dev
